import discord
from discord import app_commands
from discord.ext import commands
from database import create_key, get_key, blacklist_key, log_action
from utils import is_admin, admin_only_embed, format_key_embed


class KeysCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    # ── /genkey ──────────────────────────────────────────────────────────────
    @app_commands.command(name="genkey", description="Generate a new license key.")
    @app_commands.describe(
        duration="Duration in days (omit for lifetime key)",
        amount="How many keys to generate (1–10)",
        note="Optional note attached to the key(s)"
    )
    async def genkey(
        self,
        interaction: discord.Interaction,
        duration: int = None,
        amount: int = 1,
        note: str = None
    ):
        if not await is_admin(interaction):
            await interaction.response.send_message(embed=admin_only_embed(), ephemeral=True)
            return

        if amount < 1 or amount > 10:
            await interaction.response.send_message("❌ Amount must be between 1 and 10.", ephemeral=True)
            return

        await interaction.response.defer(ephemeral=True)

        is_lifetime = duration is None
        keys = []
        for _ in range(amount):
            key_id = await create_key(
                created_by=str(interaction.user.id),
                is_lifetime=is_lifetime,
                duration_days=duration,
                note=note
            )
            keys.append(key_id)
            await log_action("GENKEY", str(interaction.user.id), key_id,
                             f"lifetime={is_lifetime}, days={duration}, note={note}")

        embed = discord.Embed(
            title="🔑 Key(s) Generated",
            color=discord.Color.green()
        )
        embed.add_field(
            name="Type",
            value="♾️ Lifetime" if is_lifetime else f"⏳ {duration} day(s)",
            inline=True
        )
        embed.add_field(name="Amount", value=str(len(keys)), inline=True)
        if note:
            embed.add_field(name="Note", value=note, inline=False)

        key_list = "\n".join(f"`{k}`" for k in keys)
        embed.add_field(name="Keys", value=key_list, inline=False)
        embed.set_footer(text=f"Generated by {interaction.user}")

        await interaction.followup.send(embed=embed, ephemeral=True)

    # ── /keyinfo ─────────────────────────────────────────────────────────────
    @app_commands.command(name="keyinfo", description="Look up info about a key.")
    @app_commands.describe(key="The license key to inspect")
    async def keyinfo(self, interaction: discord.Interaction, key: str):
        if not await is_admin(interaction):
            await interaction.response.send_message(embed=admin_only_embed(), ephemeral=True)
            return

        await interaction.response.defer(ephemeral=True)
        data = await get_key(key.upper())
        if not data:
            await interaction.followup.send("❌ Key not found.", ephemeral=True)
            return

        embed = await format_key_embed(data, self.bot)
        await interaction.followup.send(embed=embed, ephemeral=True)

    # ── /blacklistkey ─────────────────────────────────────────────────────────
    @app_commands.command(name="blacklistkey", description="Blacklist or un-blacklist a key.")
    @app_commands.describe(key="The license key", state="True to blacklist, False to un-blacklist")
    async def blacklistkey(self, interaction: discord.Interaction, key: str, state: bool):
        if not await is_admin(interaction):
            await interaction.response.send_message(embed=admin_only_embed(), ephemeral=True)
            return

        data = await get_key(key.upper())
        if not data:
            await interaction.response.send_message("❌ Key not found.", ephemeral=True)
            return

        await blacklist_key(key.upper(), state)
        await log_action(
            "BLACKLIST_KEY" if state else "UNBLACKLIST_KEY",
            str(interaction.user.id), key.upper()
        )
        action = "blacklisted 🚫" if state else "un-blacklisted ✅"
        await interaction.response.send_message(f"Key `{key.upper()}` has been **{action}**.", ephemeral=True)


async def setup(bot):
    await bot.add_cog(KeysCog(bot))
